name: MLFlow Tracking
description: Instrumenting some scikit-learn models with MLFLow for experiment tracking.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2020-12-09"
api_version: 1

environment_variables:
  PYTHONPATH:
    default: "/home/cdsw"
    description: "Allow Python to find scripts directory when run as CLI"
    prompt_user: false

engine_images:
  - image_name: engine
    tags:
      - 14-cml-2021.05-1

runtimes:
  - editor: Workbench
    kernel: Python 3.6
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    kernel: python3
    memory: 2
    cpu: 1

  - type: create_job
    name: Train KNeighbors
    entity_label: train_kneighbors
    script: scripts/train_kneighbors.py
    arguments: None
    cpu: 1
    memory: 2
    short_summary: Create a training job for a k-nearest neighbors classifier.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3
    
  - type: run_job
    entity_label: train_kneighbors
    short_summary: Training a knn algorithm.
    long_summary: Train a k-nearest neighbors algorithm for classification on a fake dataset.
    
  - type: create_job
    name: Train Random Forest
    entity_label: train_random_forest
    script: scripts/train_random_forest.py
    arguments: None
    cpu: 1
    memory: 2
    short_summary: Create a training job for a random forest classifier.
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3
    
  - type: run_job
    entity_label: train_random_forest
    short_summary: Train a random forest algorithm.
    long_summary: Training a random forest algorithm for classification on a fake dataset.
    
  - type: start_application
    name: MLFlow UI
    subdomain: mlflow
    script: cml/mlflow_ui.py
    short_summary: Launch the MLFlow UI application
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
